// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Rq-fUMojbvlvgwQdKPLp14oIB2-dUUc',
    appId: '1:245184640165:web:82eda4191965d733a6094c',
    messagingSenderId: '245184640165',
    projectId: 'quizzle-test',
    authDomain: 'quizzle-test.firebaseapp.com',
    storageBucket: 'quizzle-test.appspot.com',
    measurementId: 'G-H4VFPC5JTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXVviEpZ63Vjt21Y9ksSU7FwFLJWePw2Q',
    appId: '1:245184640165:android:2232641f110ab7a6a6094c',
    messagingSenderId: '245184640165',
    projectId: 'quizzle-test',
    storageBucket: 'quizzle-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIU0Hhqk3_a-4f4_tpvUnsH03zFYLpQ4s',
    appId: '1:245184640165:ios:3925e404911b1afca6094c',
    messagingSenderId: '245184640165',
    projectId: 'quizzle-test',
    storageBucket: 'quizzle-test.appspot.com',
    iosClientId: '245184640165-eo6t9g0ovnqhc0g40s5dl3upclj5fri8.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
